// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: maths.proto

#include "maths.pb.h"
#include "maths.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace maths {

static const char* Maths_method_names[] = {
  "/maths.Maths/DoMathStream",
};

std::unique_ptr< Maths::Stub> Maths::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Maths::Stub> stub(new Maths::Stub(channel));
  return stub;
}

Maths::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_DoMathStream_(Maths_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::maths::MathRequest, ::maths::MathResponse>* Maths::Stub::DoMathStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::maths::MathRequest, ::maths::MathResponse>::Create(channel_.get(), rpcmethod_DoMathStream_, context);
}

::grpc::ClientAsyncReaderWriter< ::maths::MathRequest, ::maths::MathResponse>* Maths::Stub::AsyncDoMathStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::maths::MathRequest, ::maths::MathResponse>::Create(channel_.get(), cq, rpcmethod_DoMathStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::maths::MathRequest, ::maths::MathResponse>* Maths::Stub::PrepareAsyncDoMathStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::maths::MathRequest, ::maths::MathResponse>::Create(channel_.get(), cq, rpcmethod_DoMathStream_, context, false, nullptr);
}

Maths::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Maths_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Maths::Service, ::maths::MathRequest, ::maths::MathResponse>(
          std::mem_fn(&Maths::Service::DoMathStream), this)));
}

Maths::Service::~Service() {
}

::grpc::Status Maths::Service::DoMathStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::maths::MathResponse, ::maths::MathRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace maths

